services:
  - type: web
    name: bm-iluminacion
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: mongodb+srv://bmilumina:Tortuga92bmilumina.pr5eqeg.mongodb.net/
        sync: false
      - key: JWT_SECRET
        generateValue: true
